# Generated by Django 5.0.2 on 2024-02-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regtime', models.DateTimeField(auto_now_add=True, help_text='time of registeration')),
                ('image', models.ImageField(upload_to='Profile Pictures')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
