# Generated by Django 5.0.2 on 2024-02-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='we', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='wwq', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='wewe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='toue', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='opop', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='lpd2', upload_to='Profile Pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='nice', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='qwqw', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(default='wewd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='qwdqw', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='qwdw', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
