# Generated by Django 5.0.2 on 2024-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(default='11', help_text='4 digit PIN for transaction verification.', max_length=128),
            preserve_default=False,
        ),
    ]
