# Generated by Django 5.0.3 on 2024-03-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='nickname',
        ),
    ]
