# Generated by Django 5.0.3 on 2024-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_account_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='User', max_length=50, null=True),
        ),
    ]
