# Generated by Django 5.0.1 on 2024-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='id',
        ),
        migrations.AddField(
            model_name='trans',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trans',
            name='transaction_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
