# Generated by Django 5.0.1 on 2024-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_trans_id_trans_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='bank',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trans',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
