# Generated by Django 5.0.1 on 2024-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_trans_bank_alter_trans_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
